require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - lib/**/*.rb
    - test/**/*.rb

  Exclude:
    - .gitignore
    - .rubocop.yml

    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.md
    - README.md

    - script/**/*
    - vendor/**/*

Style/MultilineIfModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false